# This config setup assumes that we're running Jekyll inside Docker

destination: /build
future: true
host: 0.0.0.0
name: "Art Chaidarun"
permalink: /:slug # `:title` is apparently just an alias for `:slug`
url: https://chaidarun.com
